### ISSUE TITLE
Nice book

### ISSUE THREAD

**Issue by Dob4ig** [lancelote/interpy-ru#17]
there described some intersting moments. I would like to add something about asyncio, threading, multiprocessing. I can help translate the book english -> russian. If you are interested in this, please answer  to this issue.

**Comment by lancelote** [comment]
Hi @Dob4ig, I think it makes sense to contribute new topics to [the original book](https://github.com/yasoob/intermediatePython) first and then translate them to Russian. I would gratefully accept translation contribution, of course.
